Ajout du mode minuteur/chronometre
btssn-lasalle-84/pomodoro-2022 pull request #19
Opened 2022-06-01 07:13 UTC by testablet

2022-06-01 09:03 UTC, testablet commented
Demande de vérification et merge

2022-06-01 13:14 UTC, tvaira requested changes

2022-06-01 13:14 UTC, tvaira commented on Pomodoro/app/src/main/java/com/example/pomodoro/PomodoroActivity.java
> +        modeMinuteur();
Il faut un VERBE !!!

2022-06-01 13:14 UTC, tvaira commented on Pomodoro/app/src/main/java/com/example/pomodoro/PomodoroActivity.java
> +    private void modeSonnerie()
Il faut un VERBE !!!

2022-06-01 13:14 UTC, tvaira commented on Pomodoro/app/src/main/java/com/example/pomodoro/PomodoroActivity.java
> +        if(switchMinuteur.isChecked())
`switchMinuteur` : c'est quoi ce nom de variable !!!

2022-06-01 15:13 UTC, tvaira submitted a review, later dismissed

2022-06-02 10:07 UTC, testablet commented
Demande de vérification

2022-06-02 12:29 UTC, tvaira approved these changes

2022-06-02 12:29 UTC, tvaira commented on Pomodoro/app/src/main/java/com/example/pomodoro/PomodoroActivity.java
> +        estModeHorloge = (Switch) findViewById(R.id.switchMinuteur);
C'est toujours une forme conjuguée ! Ici, un nom approprié serait `modeFonctionnement`

2022-06-02 12:29 UTC, tvaira commented on Pomodoro/app/src/main/java/com/example/pomodoro/PomodoroActivity.java
> +        estModeSonnerie = (Switch) findViewById(R.id.switchSonnerie);
C'est toujours une forme conjuguée ! Ici, un nom approprié serait `modeSonnerie`

2022-06-02 14:16 UTC, tvaira approved these changes

2022-06-02 17:55 UTC, merged