Ajout de l'évenement vibration
btssn-lasalle-84/pomodoro-2022 pull request #22
Opened 2022-06-08 06:08 UTC by testablet

Je n'arrive pas à faire vibrer la tablette

2022-06-08 07:57 UTC, testablet commented
Devrais-je faire vibrer la tablette lors d'un évenement ou une notification est plus optimal ?
Les deux peuvent-ils être envisageable ? 
Actuellement je gère la sonnerie du pomodoro connecté mais j'aimerais pouvoir aussi avoir une trace de l'évenement visible sur la tablette (Notifications, Vibration, autre ?)

En attente de votre avis sur la question et de votre aide.
Je vous remercie par avance

2022-06-08 08:32 UTC, testablet commented
J'ai ajouté le système de notification de votre site internet, cependant je reste bloqué lors du "idNotification++"
Suis-je sur la bonne voie ?

2022-06-08 13:16 UTC, tvaira commented on Pomodoro/app/src/main/java/com/example/pomodoro/PomodoroActivity.java
> +        NotificationManager notificationManager = (NotificationManager)getSystemService(Context.NOTIFICATION_SERVICE);
Cela doit être fait une seule fois

2022-06-08 13:31 UTC, tvaira commented on Pomodoro/app/src/main/java/com/example/pomodoro/PomodoroActivity.java
> +        NotificationManager notificationManager = (NotificationManager)getSystemService(Context.NOTIFICATION_SERVICE);
Il ne faut pas le déclarer ici mais en attribut de la classe : 

```java
private NotificationManager notificationManager = null;
```

2022-06-08 14:02 UTC, testablet commented
Comment dois-je utiliser cette ligne ? 
notifierEvenement((String)message.obj);

Dois-je la mettre dans le handler ou lors d'un évenement comme la fin d'une tache par exemple ?

2022-06-09 06:18 UTC, testablet commented
Je pense avoir bien suivis vos spécifications cependant je ne comprend pas pourquoi l'application s'arrete lors de l'évenement.
Erreur de programmation ? Permission non accordée pour les notifications dans AndroidManifest.xml

2022-06-09 06:27 UTC, tvaira commented
> Je pense avoir bien suivis vos spécifications cependant je ne comprend pas pourquoi l'application s'arrete lors de l'évenement. Erreur de programmation ? Permission non accordée pour les notifications dans AndroidManifest.xml

Cela n'a pas d'intérêt si tu ne donnes pas les messages de Log !

2022-06-09 06:38 UTC, testablet commented
Voilà les logs lors de l'arret de l'application :

2022-06-09 08:31:29.318 11678-11678/com.example.pomodoro E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.pomodoro, PID: 11678
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/NotificationChannel;
        at com.example.pomodoro.PomodoroActivity.notifierEvenement(PomodoroActivity.java:793)
        at com.example.pomodoro.PomodoroActivity$8.handleMessage(PomodoroActivity.java:630)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6780)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1500)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1390)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.NotificationChannel" on path: DexPathList[[zip file "/data/app/com.example.pomodoro-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.pomodoro-2/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.example.pomodoro.PomodoroActivity.notifierEvenement(PomodoroActivity.java:793) 
        at com.example.pomodoro.PomodoroActivity$8.handleMessage(PomodoroActivity.java:630) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6780) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1500) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1390)

2022-06-09 18:28 UTC, tvaira requested changes

2022-06-09 18:28 UTC, tvaira commented on Pomodoro/app/src/main/AndroidManifest.xml
>              <intent-filter>
Non ! Une seule activité est déclarée `MAIN` (principale) et `LAUNCHER` (démarrage) : c'est `PomodoroActivity`

2022-06-09 18:54 UTC, testablet commented
L'erreur persiste toujours, voici les logs : 

2022-06-09 20:52:32.823 26241-26241/com.example.pomodoro E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.pomodoro, PID: 26241
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/NotificationChannel;
        at com.example.pomodoro.PomodoroActivity.notifierEvenement(PomodoroActivity.java:793)
        at com.example.pomodoro.PomodoroActivity$8.handleMessage(PomodoroActivity.java:630)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6780)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1500)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1390)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.NotificationChannel" on path: DexPathList[[zip file "/data/app/com.example.pomodoro-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.pomodoro-1/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.example.pomodoro.PomodoroActivity.notifierEvenement(PomodoroActivity.java:793) 
        at com.example.pomodoro.PomodoroActivity$8.handleMessage(PomodoroActivity.java:630) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6780) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1500) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1390)

2022-06-09 19:27 UTC, tvaira requested changes

2022-06-09 19:27 UTC, tvaira commented on Pomodoro/app/src/main/java/com/example/pomodoro/PomodoroActivity.java
> +        NotificationManager notificationManager = (NotificationManager)getSystemService(Context.NOTIFICATION_SERVICE);
Oh !!! `notificationManager` est un attribut de la classe !!! Il ne faut surtout pas le (re)déclarer en variable locale. Ton attribut sera toujours `null` ! Donc : 

```java
notificationManager = (NotificationManager)getSystemService(Context.NOTIFICATION_SERVICE);
```

2022-06-09 19:30 UTC, testablet commented on Pomodoro/app/src/main/java/com/example/pomodoro/PomodoroActivity.java
> +        NotificationManager notificationManager = (NotificationManager)getSystemService(Context.NOTIFICATION_SERVICE);
Et il doit bien se placer dans le onCreate(), je ne me suis pas trompé sur son positionnement ?

2022-06-09 19:30 UTC, tvaira commented
> L'erreur persiste toujours, voici les logs :
> 
> ...

La classe `NotificationChannel` n'est pas défini dans cette version API (elle apparaît à la version API 26 et ta tablette doit être en 24, à vérifier)

Donc, tu mets cette partie en commentaires :

```java
//NotificationChannel channel = new NotificationChannel("POMODORO", name, importance);
//channel.setDescription(description);
//notificationManager.createNotificationChannel(channel);
```

2022-06-09 19:44 UTC, testablet commented
Demande de fusion

2022-06-10 06:24 UTC, tvaira approved these changes

2022-06-10 06:55 UTC, merged